### ISSUE TITLE
modis2gtiff.sh unable to process IPOPP 2.5 MODIS hdf

### ISSUE THREAD

**Issue by songhan89** [davidh-ssec/polar2grid#133]
Hi David,

I'm having problem processing the hdf files using modis2gtiff.sh 

The hdf5 files are okay and can be processed by other ipopp packages. Do you have any idea what might be the problem ?

`ipopp@h8-nas:~/pub/gsfcdata/terra/modis/level1> /ess/data/software/polar2grid_v_2_0/bin/modis2gtiff.sh -f *KM.17005112745.hdf`

```
INFO     : Initializing swath extractor...
ERROR    : No useable files loaded
ERROR    : modis frontend failed to load and sort data files (see log for details)
```

```
[2017-02-24 14:52:42,933] : PID  35673 : DEBUG    : polar2grid.modis.modis_to_swath : load_files : File parsing error:
Traceback (most recent call last):
  File "/ess/data/software/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid.modis-2.0.0-py2.7.egg/polar2grid/modis/modis_to_swath.py", line 493, in load_files
    h = guidebook.HDFEOSReader(fp)
  File "/ess/data/software/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid.modis-2.0.0-py2.7.egg/polar2grid/modis/modis_guidebook.py", line 362, in __init__
    raise RuntimeError("Could not parse HDF-EOS file (see debug log for details)")
RuntimeError: Could not parse HDF-EOS file (see debug log for details)
[2017-02-24 14:52:42,933] : PID  35673 : DEBUG    : polar2grid.modis.modis_to_swath : load_files : Unrecognized file: /ess/data/drl/pub/gsfcdata/terra/modis/level1/MOD021KM.17005112745.hdf
[2017-02-24 14:52:42,934] : PID  35673 : DEBUG    : polar2grid.modis.modis_to_swath : load_files : Unrecognized file: /ess/data/drl/pub/gsfcdata/terra/modis/level1/MOD02HKM.17005112745.hdf
[2017-02-24 14:52:42,934] : PID  35673 : DEBUG    : polar2grid.modis.modis_to_swath : load_files : Unrecognized file: /ess/data/drl/pub/gsfcdata/terra/modis/level1/MOD02QKM.17005112745.hdf
[2017-02-24 14:52:42,934] : PID  35673 : ERROR    : polar2grid.modis.modis_to_swath : load_files : No useable files loaded
[2017-02-24 14:52:42,934] : PID  35673 : DEBUG    : modis2gtiff : main : Frontend exception:
Traceback (most recent call last):
  File "/ess/data/software/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid-2.0.0-py2.7-linux-x86_64.egg/polar2grid/glue.py", line 257, in main
    f = fcls(search_paths=args.data_files, **args.subgroup_args["Frontend Initialization"])
  File "/ess/data/software/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid.modis-2.0.0-py2.7.egg/polar2grid/modis/modis_to_swath.py", line 446, in __init__
    self.load_files(self.find_files_with_extensions())
  File "/ess/data/software/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid.modis-2.0.0-py2.7.egg/polar2grid/modis/modis_to_swath.py", line 518, in load_files
    raise ValueError("No useable files loaded")
ValueError: No useable files loaded
[2017-02-24 14:52:42,934] : PID  35673 : ERROR    : modis2gtiff : main : modis frontend failed to load and sort data files (see log for details)
```

**Comment by songhan89** [comment]
I'm suspecting because IPOPP's HDF is HDF5 ?

**Comment by davidh-ssec** [comment]
Polar2Grid currently only supports the MODIS L1B HDF-EOS format. It determines if it can handle the provided files by their filenames. The Polar2Grid documentation describes the accepted filenames in section 5.1 of the v2.0 documentation. If your files are formatted in the right way then the simplest solution may be to rename them to one of these supported filename schemes (IMAPP or NASA Standard). Also, sorry for taking so long to reply I've been out sick.

**Comment by songhan89** [comment]
Hi David,

Thanks for answering the question. Apologise for overlooking that in the doc.

It worked simply by renaming the .hdf
