### ISSUE TITLE
AVHRR L1b reader error from numpy Size not multiple of data-type size

### ISSUE THREAD

**Issue by howff** [davidh-ssec/polar2grid#141]
I get this error: ValueError: Size of available data is not a multiple of the data-type size
I wonder if it's a pixel-packing problem, i.e. the avhrr pixels are packed into words in a different way?
The reason I say that is because the L1b file is smaller than that produced by AAPP. 

```
[2018-01-25 11:02:50,390] : PID   7648 : DEBUG    : avhrr2gtiff : main : Starting script with arguments: /packages/cspp/polar2grid_v_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/glue.py avhrr gtiff -f noaa19/sat82.l1b -vv
[2018-01-25 11:02:50,390] : PID   7648 : INFO     : avhrr2gtiff : main : Initializing reader...
[2018-01-25 11:02:50,390] : PID   7648 : DEBUG    : polar2grid.avhrr.avhrr2swath : __init__ : Day fraction set to 0.100000
[2018-01-25 11:02:50,390] : PID   7648 : DEBUG    : polar2grid.avhrr.avhrr2swath : __init__ : SZA threshold set to 100.000000
[2018-01-25 11:02:50,392] : PID   7648 : DEBUG    : polar2grid.avhrr.avhrr2swath : load_files : Could not parse .l1b file as AVHRR AAPP file: /data/scratch/tmp/reproject/noaa19/sat82.l1b
[2018-01-25 11:02:50,392] : PID   7648 : DEBUG    : polar2grid.avhrr.avhrr2swath : load_files : File parsing error: 
Traceback (most recent call last):
  File "/packages/cspp/polar2grid/common/ShellB3/lib/python2.7/site-packages/polar2grid/avhrr/avhrr2swath.py", line 129, in load_files
    h = readers.AVHRRReader(fp)
  File "/packages/cspp/polar2grid/common/ShellB3/lib/python2.7/site-packages/polar2grid/avhrr/readers.py", line 249, in __init__
    data = numpy.memmap(fp_, dtype=_SCANTYPE, offset=22016, mode="r")
  File "/packages/cspp/polar2grid/common/ShellB3/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/memmap.py", line 232, in __new__
    raise ValueError("Size of available data is not a "
ValueError: Size of available data is not a multiple of the data-type size.
[2018-01-25 11:02:50,393] : PID   7648 : DEBUG    : polar2grid.avhrr.avhrr2swath : load_files : Unrecognized file: /data/scratch/tmp/reproject/noaa19/sat82.l1b
[2018-01-25 11:02:50,393] : PID   7648 : ERROR    : polar2grid.avhrr.avhrr2swath : load_files : No useable files loaded
[2018-01-25 11:02:50,393] : PID   7648 : DEBUG    : avhrr2gtiff : main : Frontend exception: 
Traceback (most recent call last):
  File "/packages/cspp/polar2grid_v_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/glue.py", line 280, in main
    f = fcls(search_paths=args.data_files, **args.subgroup_args["Frontend Initialization"])
  File "/packages/cspp/polar2grid/common/ShellB3/lib/python2.7/site-packages/polar2grid/avhrr/avhrr2swath.py", line 107, in __init__
    self.load_files(self.find_files_with_extensions())
  File "/packages/cspp/polar2grid/common/ShellB3/lib/python2.7/site-packages/polar2grid/avhrr/avhrr2swath.py", line 154, in load_files
    raise ValueError("No useable files loaded")
ValueError: No useable files loaded
[2018-01-25 11:02:50,394] : PID   7648 : ERROR    : avhrr2gtiff : main : avhrr frontend failed to load and sort data files (see log for details)
```

File available from:
https://wetransfer.com/downloads/67201780521ed9abf5e71c25e68ccf4020180125110657/609f5b81561ecfc455686f8f3c74b87520180125110657/0da4f8

**Comment by davidh-ssec** [comment]
See #140 for more details. NOAA AVHRR format is not supported by Polar2Grid at this time. In the future it could be, but must be added to SatPy first.
